/*--------- Test task ---------*/

var gulp = require('gulp');

gulp.task('hello', function() {
  console.log('Hello Zell');
});

/*---------  Sass ---------*/

var sass = require('gulp-sass');

gulp.task('sass', function(){
  return gulp.src('app/sass/**/*.scss')
    .pipe(sass()) 
    .pipe(gulp.dest('app/css'))
    .pipe(browserSync.reload({
      stream: true
    }))
});

gulp.task('watch', ['browserSync', 'sass'], function (){
	gulp.watch('app/sass/**/*.scss', ['sass']);
	gulp.watch('app/*.html', browserSync.reload); 
  	gulp.watch('app/js/**/*.js', browserSync.reload);  
});

/*--------- BrowserSync ---------*/

var browserSync = require('browser-sync').create();

gulp.task('browserSync', function() {
  browserSync.init({
    server: {
      baseDir: 'app'
    },
  })
})

/*--------- Concatenation and Minifying ---------*/

var useref = require('gulp-useref');
var uglify = require('gulp-uglify');
var gulpIf = require('gulp-if');
var cssnano = require('gulp-cssnano');

gulp.task('useref', function(){
  return gulp.src('app/*.html')
    .pipe(useref())
    // Minifies only if it's a JavaScript file
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulpIf('*.css', cssnano()))
    .pipe(gulp.dest('dist'))
});

/*--------- Optimizing images ---------*/

var imagemin = require('gulp-imagemin');
var cache = require('gulp-cache');

gulp.task('images', function(){
  return gulp.src('app/img/**/*.+(png|jpg|jpeg|gif|svg)')
  // Caching images that ran through imagemin
  .pipe(cache(imagemin({
      interlaced: true
    })))
  .pipe(gulp.dest('dist/img'))
});

//Clear cache
gulp.task('cache:clear', function (callback) {
return cache.clearAll(callback)
})

/*--------- Copying fonts to dist folder ---------*/

gulp.task('fonts', function() {
  return gulp.src('app/fonts/**/*')
  .pipe(gulp.dest('dist/fonts'))
})

/*--------- Deleting autogenerated files ---------*/

var del = require('del');

gulp.task('clean:dist', function() {
  return del.sync('dist');
})

/*--------- Combining all tasks ---------*/

var runSequence = require('run-sequence');

gulp.task('build', function (callback) {
  runSequence('clean:dist', 
    ['sass', 'useref', 'images', 'fonts'],
  )
})

gulp.task('default', function (callback) {
  runSequence(['sass','browserSync', 'watch'],
  )
})